version: '1.21.2'
services:
 minecraft:
   ports:
     - "19132:19132"
   environment:
     TZ: "Australia/Melbourne"
     VERSION: "1.21.2.02"
     PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
     LD_LIBRARY_PATH: "."
   deploy:
     resources:
       limits:
         memory: 8G
   volumes:
     - "~/your-dir:/bedrock-server/data"
   stdin_open: true
   tty: true
